import {
  IsDate,
  IsEmail,
  IsEnum,
  IsNumber,
  IsOptional,
  IsString,
  IsUrl,
  MinLength,
} from 'class-validator';

import { Role } from '../entity/user.entity';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class RegisterUserDto {
  @IsString()
  @ApiProperty({
    description: 'Name of the user (STUDENT or MODERATOR)',
    example: 'Swapnil',
  })
  name!: string;

  @IsEmail()
  @ApiProperty({
    description: 'Email of the user (STUDENT or MODERATOR)',
    example: 'swapnil123@gmail.com',
  })
  email!: string;

  @IsOptional()
  @IsNumber()
  @ApiPropertyOptional({
    description:
      'Roll number (required for STUDENT not required for MODERATOR)',
    example: 1,
    type: Number,
  })
  rollNo?: number;

  @MinLength(6)
  @ApiProperty({
    description: 'Password (minimum length 6)',
    example: 'abcdef',
  })
  password!: string;

  @IsEnum(Role)
  @ApiProperty({
    enum: Role,
    default: Role.student,
    description: 'Role of the user (STUDENT or MODERATOR)',
    example: Role.student,
  })
  role!: Role;
}

export class RegisterUserResponseDto {
  @IsNumber()
  @ApiProperty({
    description: 'User Id generated by database',
    example: 1,
  })
  userId!: number;

  @IsString()
  @ApiProperty({
    description: 'Name of the user (STUDENT or MODERATOR)',
    example: 'Swapnil',
  })
  name!: string;

  @IsEmail()
  @ApiProperty({
    description: 'Email of the user (STUDENT or MODERATOR)',
    example: 'swapnil123@gmail.com',
  })
  email!: string;

  @IsOptional()
  @IsNumber()
  @ApiPropertyOptional({
    description:
      'Roll number (required for STUDENT not required for MODERATOR)',
    example: 1,
    type: Number,
  })
  rollNo?: number;

  @IsEnum(Role)
  @ApiProperty({
    enum: Role,
    default: Role.student,
    description: 'Role of the user (STUDENT or MODERATOR)',
    example: Role.student,
  })
  role!: Role;

  @IsUrl()
  @IsOptional()
  @ApiProperty({
    description:
      'Profile photo URL of user. null initially, to be set using POST /user/upload route later',
  })
  profilePhotoUrl!: string;

  @IsDate()
  @ApiProperty({
    description: 'Timestamp when user is first created',
  })
  createdAt!: Date;

  @IsDate()
  @ApiProperty({
    description: 'Timestamp when user was last logged in',
  })
  updatedAt!: Date;
}
